sudo: false

language: c

addons:
    apt:
        packages:
        - libgmp-dev

cache:
    directories:
    - $HOME/.stack/

env:
- STACK_ARGS=
- STACK_ARGS="--resolver nightly"

matrix:
    fast_finish: true
    allow_failures:
    - env: STACK_ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip=1 -C ~/.local/bin '*/stack'

install:
- travis_wait stack $STACK_ARGS --no-terminal --skip-ghc-check setup
- travis_wait stack $STACK_ARGS --no-terminal --skip-ghc-check test --only-snapshot
- stack --resolver lts install hlint

script:
- stack $STACK_ARGS --no-terminal --skip-ghc-check test --test --copy-bins
- hlint .
- git fmt -m dry-run --operate-on-tracked
